# Generated by Django 3.2.7 on 2021-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100, verbose_name='Nome do curso')),
                ('slug_course', models.SlugField(verbose_name='Atalho')),
                ('description_course', models.TextField(verbose_name='Descrição do curso')),
                ('image_course', models.ImageField(upload_to='course_img/%Y/%m/%d', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
