# Generated by Django 3.2.7 on 2021-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20211106_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='identificador'),
            preserve_default=False,
        ),
    ]
