# Generated by Django 3.2.7 on 2021-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='identificador'),
        ),
    ]
