# Generated by Django 3.2.7 on 2021-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description_course',
            field=models.TextField(blank=True, verbose_name='Descrição do curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(blank=True, null=True, upload_to='course_img/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
