# Generated by Django 3.2.7 on 2021-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_course_image_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.CharField(default=1, max_length=255, verbose_name='Sobre o curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=50, verbose_name='Nome do curso'),
        ),
    ]
