# Generated by Django 3.2.7 on 2021-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_auto_20211005_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_course',
            field=models.TextField(verbose_name='Sobre o curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_course',
            field=models.CharField(max_length=255, verbose_name='Descrição do curso'),
        ),
    ]
