# Generated by Django 3.2.7 on 2021-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug_course',
            field=models.SlugField(blank=True, verbose_name='Atalho'),
        ),
    ]
