# Generated by Django 3.2.7 on 2021-10-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_auto_20211018_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adverts',
            new_name='Advert',
        ),
    ]
