# Generated by Django 3.2.7 on 2021-10-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_auto_20211021_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Análise'), (1, 'Aprovado'), (2, 'Cancelado')], default=0, verbose_name='Situação'),
        ),
    ]
